name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Build binaries
      run: |
        GOOS=windows GOARCH=amd64 go build -o task.exe
        GOOS=darwin GOARCH=amd64 go build -o task-darwin
        GOOS=linux GOARCH=amd64 go build -o task-linux
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          task.exe
          task-darwin
          task-linux